### PR TITLE
Pin excon gem to ~> 0.64

### PR DESCRIPTION
**Pull request by drewhammond**
excon 1.0.0 was released today (https://github.com/excon/excon/commit/33a071d992f04350c12918a9b259154df35c5332) and this has caused conflicts in our environment with `fog-core`.

Would you consider changing the constraint to `~> 0.64` until the next major release?

### CODE REVIEW

**Comment by joseph-burns** [comment]
@drewhammond were you able to find any workaround here?  We're having the same issue

**Comment by drewhammond** [comment]
@joseph-burns Unfortunately none of our attempted workarounds helped so we ended up just hotfixing the gem with my changes here and are now serving that version from artifactory internally.

**Comment by geemus** [comment]
Sorry to hear this is causing issues. I thought that fog-core would be able to resolve an earlier excon if needed, which would buy me a little time to do some fixes in fog-aws before bumping in fog-core too.

Could you tell me a bit more about the conflicts you are seeing and/or can you share a simple repro case? That would really help in terms of pinning down a workaround.

If you need to pin, I think anything up to `~>0.112` should be fine and compatible with fog-core, and higher is probably better (as 0.64 is quite old at this point).

Otherwise, I plan to bump fog-core's dependency, but need first to do some fog-aws updates as otherwise there would be behavior changes. Hoping to get to all of that in the next few days, and had hoped it would be ok (and not cause issues like this). Apologies for that, hopefully it will at least be short lived.

**Comment by joseph-burns** [comment]
@geemus the issue is that since `docker-api` is locked to `>= 0.64.0`, and `fog-core` is locked to `~> 0.64.0`, they'll never match now that there is a new major version of `excon` (which released `1.0.0` today).
`1.0.0` matches the `docker-api` constraint, but not the `fog-core` constraint (`~>` means it is the same major version, but equal or higher minor/patch versions, where `=>` means it can be anything higher or equal, including higher major versions).
When chef client executes, it will install both, actually, but it isn't smart enough to not break when installing `fog-core`, and tries to use `1.0.0` in both cases.

**Comment by geemus** [comment]
Do you know how chef client decides that?

I was trying with bundler and it's able to resolve them the way I would expect. ie if I create a gemfile with `docker-api` and `fog-aws`, I end up with a lockfile that has excon v0.112.0 (which matches both of the constraints). I thought in general that this is how it worked, and it's why I didn't anticipate this sort of problem.

**Comment by ls-todd-lunter** [comment]
Both `>= 0.64.0` and `~> 0.64.0` are compatible, so I'm confused on why chef is forcing the install of `1.0.0`. It seems like this fix would only work if these were your only two dependencies that used `excon` which feels like it might not be the case (I don't use chef).

Given the current gem requirements though, I don't feel like we can adjust the version down. Is there any chef support that details why the version enforcement works this way?

**Comment by geemus** [comment]
Any chance you also have `faraday-excon` in the Gemfile? I bumped it to look for 1.0.0 specifically, but you could lock it to the previous version.

**Comment by joseph-burns** [comment]
> Any chance you also have `faraday-excon` in the Gemfile? I bumped it to look for 1.0.0 specifically, but you could lock it to the previous version.

I am checking on that.  I believe we are (because we're also using bundler, rake, and probably others)
```
Gem excon-0.110.0
  activesupport (>= 0, development)
  delorean (>= 0, development)
  eventmachine (>= 1.0.4, development)
  json (>= 1.8.5, development)
  open4 (>= 0, development)
  puma (>= 0, development)
  rake (>= 0, development)
  rspec (>= 3.5.0, development)
  shindo (>= 0, development)
  sinatra (>= 0, development)
  sinatra-contrib (>= 0, development)
  webrick (>= 0, development)

Gem excon-0.112.0
  activesupport (>= 0, development)
  delorean (>= 0, development)
  eventmachine (>= 1.0.4, development)
  json (>= 1.8.5, development)
  open4 (>= 0, development)
  puma (>= 0, development)
  rake (>= 0, development)
  rspec (>= 3.5.0, development)
  shindo (>= 0, development)
  sinatra (>= 0, development)
  sinatra-contrib (>= 0, development)
  webrick (>= 0, development)

Gem excon-1.0.0
  activesupport (>= 0, development)
  delorean (>= 0, development)
  eventmachine (>= 1.0.4, development)
  json (>= 1.8.5, development)
  open4 (>= 0, development)
  puma (>= 0, development)
  rake (>= 0, development)
  rspec (>= 3.5.0, development)
  shindo (>= 0, development)
  sinatra (>= 0, development)
  sinatra-contrib (>= 0, development)
  webrick (>= 0, development)
  
  
/opt/chef/embedded/bin/./gem dependency faraday-excon
Gem faraday-excon-1.1.0
  bundler (~> 2.0, development)
  excon (>= 0.27.4, development)
  faraday (~> 1.0, development)
  multipart-parser (~> 0.1.1, development)
  rake (~> 13.0, development)
  rspec (~> 3.0, development)
  rubocop (~> 0.91.1, development)
  rubocop-packaging (~> 0.5, development)
  rubocop-performance (~> 1.0, development)
  simplecov (~> 0.19.0, development)
  webmock (~> 3.4, development)
  ```

**Comment by joseph-burns** [comment]
> Both `>= 0.64.0` and `~> 0.64.0` are compatible, so I'm confused on why chef is forcing the install of `1.0.0`. It seems like this fix would only work if these were your only two dependencies that used `excon` which feels like it might not be the case (I don't use chef).
> 
> Given the current gem requirements though, I don't feel like we can adjust the version down. Is there any chef support that details why the version enforcement works this way?

They should be compatible, but they're not equivalent.  
It looks like we're getting `1.0.0` installed because of the `docker-api` gem, but the `fog-core` gem needs major version `0`.

**Comment by geemus** [comment]
Does it consider and install them separately? How do you tell it which gems to use? (I haven't used chef in about 15-16 years, so my memory is fuzzy to non-existent)

**Comment by geemus** [comment]
I guess are the gems being installed via a cookbook? (sorry just trying to understand)

**Comment by joseph-burns** [comment]
Yeah - I think the chef client is trying to figure out what all gems all of the cookbooks combined will need.
So, it see the constraint for docker-api, decides it wants to use 1.0.0 for excon (which, per the constraint is fine).
Then later it wants to also install fog-core, and that constraint restricts the major version to 0 of excon (which, for the last 15 years until today was fine - since there was no 1.0.0).

**Comment by geemus** [comment]
Yeah. I was wondering if there was a way to reverse the order of them, for instance. Since fog would then ask for v0.112.0.

**Comment by joseph-burns** [comment]
We're currently trying to work around by making a fork of this repo, docker chef cookbook repo, changing the dependency here to lock to the major version (like this pr does).
Then our cookbooks are updated to point to our fork of that docker cookbook, which is updated to use the fork of this gem.
The above seems like we can get the chef client to work.

**Comment by geemus** [comment]
Thanks for sharing and sorry to hear it's so complicated. I'll try to get updated/compatible versions for fog soon so that you can get back to something simpler. And it will likely be a while before any more major releases.

**Comment by ls-todd-lunter** [comment]
@joseph-burns are the gems installed independently? Like are there two separate cookbooks, one that uses fog and another that uses docker-api? And the issue is that they're both being installed on the same host, but at different times?

**Comment by joseph-burns** [comment]
> @joseph-burns are the gems installed independently? Like are there two separate cookbooks, one that uses fog and another that uses docker-api? And the issue is that they're both being installed on the same host, but at different times?

They're both referenced by the "role"'s cookbook.  Generally, one role might be composed of many cookbooks (or parts of cookbooks).  They're all installed by running the main role - but of course that's done sequentially.  
You're maybe right that we could try to install them in a different order, but the `fog-core` gem seemed to always want to use whatever the "latest" version was that was present on the machine.  I think we'd have had to uninstall/reinstall the gem a bunch of times?

**Comment by ls-todd-lunter** [comment]
Yea, I was mostly thinking if there was a way to force chef to see the gem requirements of both `docker-api` and the `fog-*` gems at the same time, and have it resolve that way. I am also, unfortunately, very unaware of how the chef ecosystem works, so I don't really know what levers there are to force it to see the dependency trees.

**Comment by geemus** [comment]
@joseph-burns thanks for the details. I hope that solves it for you for now. I am hoping to get a patch for fog-* and releases tomorrow morning my time if everything goes well. That should fix the incompatibility and allow for that to loosen the excon constraint and thereby resolve this hopefully.

**Comment by geemus** [comment]
I just released fog-core v2.6.0 which uses excon 1.0 and I think will address this. I also released fog-aws v3.29.0 which also does similar bumps. Hopefully that will resolve it for you, took me a few failed attempts to get there so I'm hoping that will be a good setup.

**Comment by ls-todd-lunter** [comment]
@joseph-burns @drewhammond Is this all set now?

**Pull request closed without merging**
